// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UDPListener.Data.Data;

#nullable disable

namespace UDPListener.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UDPListener.Data.Models.IPAddress", b =>
                {
                    b.Property<Guid>("IPAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IPAddressId");

                    b.ToTable("IPAddresses");
                });

            modelBuilder.Entity("UDPListener.Data.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IPAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MessageId");

                    b.HasIndex("IPAddressId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("UDPListener.Data.Models.Message", b =>
                {
                    b.HasOne("UDPListener.Data.Models.IPAddress", "IPAddress")
                        .WithMany("MessagesTexts")
                        .HasForeignKey("IPAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IPAddress");
                });

            modelBuilder.Entity("UDPListener.Data.Models.IPAddress", b =>
                {
                    b.Navigation("MessagesTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
